### ISSUE TITLE
Migrate `request` package to another alternative package.

### ISSUE THREAD

**Issue by namdien177** [dkatavic/onedrive-api#30]
Since `request` [was deprecated](https://github.com/request/request/issues/3142) so I suggest we should move on with a new HTTP request package.

There are plenty of packages for HTTP requests out there and we can look at what `request` suggested to replace itself [here](https://github.com/request/request/issues/3143). I would suggest using `node-fetch` as a replacement because:
- It's the lightest in the list.
- Promise/stream-based, we can now migrate all APIs to promise to have a standard.

However, I also want to promote a new option as it is very promising - `got`. [Their comparison to other package seems very good](https://github.com/sindresorhus/got#comparison).

**Comment by steffanhalv** [comment]
It would be nice to rewrite the upload method to a writeStream at the same time: https://github.com/dkatavic/onedrive-api/issues/28

**Comment by namdien177** [comment]
The owner still nowhere to be found so we should just do it ourselves first then I suppose?

Btw do you have any sample code for the ideal of `writeStream` in the upload process?

**Comment by steffanhalv** [comment]
> The owner still nowhere to be found so we should just do it ourselves first then I suppose?
> 
> Btw do you have any sample code for the ideal of `writeStream` in the upload process?

I created a pull request #31 which adds this (still using request though).

**Comment by dkatavic** [comment]
Hi @namdien177 , sorry for not coming back to this, I was busy last month

I like both options, `got` install size seems a bit big, but it is fine for me as it is still 3x smaller than `request`. Are you willing to submit PR for this?

**Comment by namdien177** [comment]
I'm actually also new to `got` and therefore have to research about it. And because changing the HTTP library is a huge deal, therefore I think we don't need to rush it 😄.
I'm not guarantee when to submit a new PR for this but I will do this when I can.
