### ISSUE TITLE
uploadSimple()'s param filename that contains '(' character will return 400

### ISSUE THREAD

**Issue by CyrusNG** [dkatavic/onedrive-api#37]
I found one issue, but I am not sure whether this is onedrive-api bug or Microsoft oneDrive API bug.

**Issue:** call uploadSimple() with filename that contains '(' character, Microsoft Graph return 400

```
oneDriveAPI.items.uploadSimple({
  accessToken: accessToken,
  filename: '10-testing(2).png',
  readableStream: readableStream
}).then((item) => {
  // console.log(item);
  // returns body of https://dev.onedrive.com/items/upload_put.htm#response
});
```

**Comment by namdien177** [comment]
This seems to be [a special case](https://github.com/OneDrive/onedrive-api-docs/issues/565) in which you have to have some workaround before passing it to the API because we pass the raw value to the API caller without parsing it.

**Comment by dkatavic** [comment]
This solution should fix the OData special character issue and it shouldn't break the existing implementation. Let me know if I am missing something
https://github.com/dkatavic/onedrive-api/pull/40
