### ISSUE TITLE
Add support to auth/move/copy

### ISSUE THREAD

**Issue by YuriSizuku** [dkatavic/onedrive-api#38]
I find there are copy and move api
https://docs.microsoft.com/ja-jp/onedrive/developer/rest-api/api/driveitem_move?view=odsp-graph-online
https://docs.microsoft.com/ja-jp/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online

please add these apis

And,  I fount it difficult to get the access token, After trying, Please also add auth.
 I try to use refresh_token to get access_token and succeed.  But I didn't find easy way to get the refresh_token. 

async function odauth(client_id, client_secret, refresh_token){
    var res=null;
    try {
        res =  await axios.post("https://login.microsoftonline.com/common/oauth2/v2.0/token" , new URLSearchParams({
            client_id: client_id, 
            client_secret: client_secret,
            refresh_token: refresh_token,
            grant_type: "refresh_token"
        }).toString(),  {
            headers : {
               "Content-Type": "application/x-www-form-urlencoded"
            }, 
        })
    } catch(e){
        console.log("odauth error!")
        console.log(e)
    }
    return res
}

**Comment by namdien177** [comment]
This library is just a wrapper around the resource API of Azure.
For authentication, you have to do it manually, as it's not a part of the resource API.
I can suggest you some lightweight and simple library to do that ([`simple-oath2`](https://github.com/lelylan/simple-oauth2)).

Another reason is that most project will be using their own implementation to authenticate, so integrate it will be redundant.

**Comment by YuriSizuku** [comment]
> This library is just a wrapper around the resource API of Azure.
> For authentication, you have to do it manually, as it's not a part of the resource API.
> I can suggest you some lightweight and simple library to do that ([`simple-oath2`](https://github.com/lelylan/simple-oauth2)).
> 
> Another reason is that most project will be using their own implementation to authenticate, so integrate it will be redundant.
> 
> About the `copy`/`move` API, I (or @dkatavic ) will work on that.

Thank you for your reply, it is very helpful to use simple-oath2 !
