### ISSUE TITLE
how to run this code ??

### ISSUE THREAD

**Issue by sharathNannur** [dkatavic/onedrive-api#4]

**Comment by dkatavic** [comment]
@sharathNannur sorry for late reply, somehow I have missed it. To run the code just follow the example. Only thing you would need is oneDrive `accessToken`. Authentication is not a part of this module, as there are already more than enough excellent libraries that solve that issue ([passport.js](http://passportjs.org/) )

**Comment by securityvoid** [comment]
Are there any simple ways to create a permanent access token that will be used by a server that will ONLY ever run as a single user and not in a multi-user/multi-tenant environment?

I've found a ton of guides on how to create AccessToken flows using full Oauth, but I really just want one static value for a very specific thing.

**Comment by dkatavic** [comment]
@securityvoid unfortunately no (or at least I didn't find one). If it is of any help, you can easily get access token for Graph API using graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by yyman001** [comment]
如果能更新好的说明如何获取token,会更有帮助
