### ISSUE TITLE
List all files

### ISSUE THREAD

**Issue by hbi99** [dkatavic/onedrive-api#41]
Hi,
This is not necessarily an issue with this library. The method **listChildren** lists immediate children to given item id. Though, Microsoft does not seem to provide a way to get children regardless of "depth" (as far as I can see in the documentation). In other words, in order to get all children, one needs to do make recursive calls to get all files.

Through the Graph Explorer, I experimented with **expand** parameter but it does not seem to result in desired outcome. Neither does it work to **search** with asterisk.

Is the Graph API this un-evolved or have I missed a lot of documentation?

Thanks in advance

**Comment by dkatavic** [comment]
Hi @hbi99 . AFAIK there is no way of getting all children of children in one API call. It could result in a big response so it is not surprising it is not implemented
