### ISSUE TITLE
Cannot list activities using list activities 

### ISSUE THREAD

**Issue by nermineslimane** [dkatavic/onedrive-api#48]
Whenever i try to list activities from y drive I get this error:
Unexpected token { in JSON at position 1 in \"https://graph.microsoft.com/v1.0//drives/11acf151067914b5/items/11ACF151067914B5!11408/activities\
here's my code
```

`exports.listActivities = async (req, res) => {
  let accessToken = await check_auth(req, res);
  let { drive_id, item_id } = req.body;
  oneDriveAPI.items
    .customEndpoint({
      accessToken: accessToken,
      url: `/drives/${drive_id}/items/${item_id}/activities`,
      method: 'GET',
      // body: {}
    })
    .then((r) => {
      res.status(200).send({ activities: r });
    })
    .catch((e) => {
      res.status(500).send({ error: e.message });
    });
};`
```
![image](https://user-images.githubusercontent.com/37881219/135060749-3b073338-5dff-4b38-af33-7ab091cfb63a.png)

and if itry to use this URL : GET /me/drive/activities
it returns 400 BAD request I couldn't understand why 
![image](https://user-images.githubusercontent.com/37881219/135060903-d0741841-0fd1-49ad-b95c-38eb6100b8b5.png)

does any one have any suggestion?

**Comment by taducquang** [comment]
https://graph.microsoft.com/v1.0//drives/11acf151067914b5/items/11ACF151067914B5!11408/activities

==> There's double "//" after v1.0, also if you can't your activities via Postman, try to check the references with Microsoft Graph REST API v1.0
