### ISSUE TITLE
Create Share Link File OneDrive

### ISSUE THREAD

**Issue by nttu307** [dkatavic/onedrive-api#49]
Hi,  OneDrive API module for Node.js of yours. It's have a function to create a shared link  ?

**Comment by dkatavic** [comment]
Hi, it doesn't have that capability but you can use customEndpoint and https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online

https://github.com/dkatavic/onedrive-api#itemscustomendpoint

If you have time to submit create shared link feature I will be happy to add it :)

**Comment by nttu307** [comment]
thanks for your answer, I was using the way you suggest :)

**Comment by paradix** [comment]
@nttu307 could you share a snippet of your code. I am trying to use customEndpoint but I'm getting HTTPError: Response code 400 (Bad Request) all the time
