### ISSUE TITLE
uploadSimple not working in nodejs 16

### ISSUE THREAD

**Issue by LPHuynh** [dkatavic/onedrive-api#50]
Below is a sample code, which works under nodejs 14, but not nodejs 16.
There seem to be an issue when passing a stream created by createReadStream() in nodejs 16.

```
const fs = require('fs')
const oneDriveAPI = require('onedrive-api')

const testRun = () => {
  const accessToken = '***insert access token here***'
  const filePath = './test.txt'
  const stream = fs.createReadStream(filePath)
  const fileName = 'test-file.txt';

  return oneDriveAPI.items.uploadSimple({
    accessToken: accessToken,
    filename: fileName,
    readableStream: stream
  })
    .then((item) => {
      console.log(item)
      stream.destroy();
    })
    .catch((error) => {
      console.log(error)
      stream.destroy();
    })
};

testRun().then(() => process.exit());
```

edit: 

additional info: I'm using node v16.13.1 on windows 10. 

uploadSimple stalls for a few minute before timing out with the following error: 

```
RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (C:\test\node_modules\got\dist\source\core\index.js:957:25)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (C:\test\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1639767749393,
    socket: 1639767749398,
    lookup: 1639767749413,
    connect: 1639767749448,
    secureConnect: 1639767749511,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1639767870576,
    abort: undefined,
    phases: {
      wait: 5,
      dns: 15,
      tcp: 35,
      tls: 63,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 121183
    }
  }
}
```

**Comment by dkatavic** [comment]
hi @LPHuynh . Have you managed to resolve it? I'm testing on v16.13.1 on Mac and sample you provided works fine. Can you try different v16 Node version?

**Comment by LPHuynh** [comment]
hi @dkatavic, I tried several different versions, and here are the results. Tested under windows and ubuntu 20.04:

14.17.4 - works
16.0.0 - does not work
16.12.0 - does not work
16.13.0 - does not work
16.13.1 - does not work
17.0.0 - does not work
17.2.0 - does not work

**Comment by dkatavic** [comment]
@LPHuynh  I have tried the exact example on Windows and Node16 and it works for me, but I think I figured out the issue. Once I changed file permissions on `'./test.txt'` file I could reproduce it, I think that Node16 doesn't have read permissions on the file, that is why it is throwing this error, it could connect to graphAPI but ` firstByte: undefined,` indicated that we sent nothing to the server. Can you make sure that Node16 has read permissions on the file and try again?

**Comment by LPHuynh** [comment]
I checked and the file permission is set correctly. Tried with a different files/file type. Cleared everything and updated onedrive-api 1.0.1->1.0.3,  so I have a fresh copy of everything. Still no dice...

**Comment by dkatavic** [comment]
Hi @LPHuynh , sorry for late response, I was out. Have you managed to resolve it?

**Comment by seufernandez** [comment]
@LPHuynh I'm facing the same problem 😅

**Comment by LPHuynh** [comment]
@dkatavic Sorry, I couldn't figure out any workaround for this. I didn't spend much time on it before we decided to forgo the feature in our app. 

I wouldn't mind closing the issue if you were not able to replicate it, but it seem @seufernandez was able to confirm and likely need help with it. It's a weird bug for sure 😅

**Comment by dkatavic** [comment]
@LPHuynh thanks for taking the time to look at it. You can leave it open as it is not an isolated incident. 

@LPHuynh @seufernandez do you remember how did you install Node on Windows? I'm still struggling to reproduce it, there seems to be no breaking Node16 change

**Comment by LPHuynh** [comment]
Linux I installed via nvm (https://github.com/nvm-sh/nvm).
Windows: nvm-windows (https://github.com/coreybutler/nvm-windows).

**Comment by dkatavic** [comment]
@seufernandez interesting. I'm tight with time, but I will try to replicate it on my machine

**Comment by dkatavic** [comment]
I think I found the issue, it is because of the way Stream behaves in NodeJS16, there were similar issues with got. I will test it out and push change

**Comment by dkatavic** [comment]
@seufernandez @LPHuynh this should be fixed now. Let me know if it doesn't work for you
