### ISSUE TITLE
Depending on vulnerable version of `got`

### ISSUE THREAD

**Issue by nilswsr** [dkatavic/onedrive-api#70]
As the HTTP request library `got` is pure ESM since [v12](https://github.com/sindresorhus/got/releases/tag/v12.0.0), the version of `got` can't be bumped, meaning the `onedrive-api` module depends on a vulnarable version.

As far as I see it, there are three options:
1. Convert to ESM as well
2. Try and use a dynamic import (requires async context)
3. Change request library

What is your take on this?
I would be willing to work on this.

**Comment by paradix** [comment]
I did try a rewrite to @hapi/wreck and it works nice and the changes are not very complex

**Comment by nilswsr** [comment]
> I did try a rewrite to @hapi/wreck and it works nice and the changes are not very complex

Sounds good! @dkatavic What is your take on this?

**Comment by dkatavic** [comment]
@nilswsr I haven't been using NodeJS professionally lately so I will trust you on this. Will async context break backward compatibility?

**Comment by nilswsr** [comment]
> @nilswsr I haven't been using NodeJS professionally lately so I will trust you on this. Will async context break backward compatibility?

As far as I see it, only download would be breaking. Everything else already is in an async context. Download currently returns `ReadableStream` and would return `Promise<ReadableStream>` in the future.
